### ISSUE TITLE
Offline JWT validation

### ISSUE THREAD

**Issue by ccoeurderoy** [ferrerojosh/nest-keycloak-connect#62]
Hi,

I'm using this great NestJS module to connect Keycloak to my backend microservice and I've noticed that the `Auth` guard only applies online JWT validation:

https://github.com/ferrerojosh/nest-keycloak-connect/blob/f3ce791e6582549f1546abd13a33067cf4d9e8ef/src/guards/auth.guard.ts#L78

If I'm not wrong, the [keycloak-connect](https://github.com/keycloak/keycloak-nodejs-connect) lib has also a [`validateToken`](https://github.com/keycloak/keycloak-nodejs-connect/blob/f8e011aea5021b81cd085df078eee7b5d773d0cc/middleware/auth-utils/grant-manager.js#L415) method able to validate JWT offline, if the `publicKey` is defined.

Do you plan to add the offline validation in the Auth guard?

**Comment by ferrerojosh** [comment]
Yes I'll add a method of token validation along with #40

**Comment by lieberlois** [comment]
Hi @ferrerojosh ,

I just tried using the new token validation disable method in development like this:

```typescript
KeycloakConnectModule.register({
      authServerUrl: 'http://keycloak:8080/auth',
      realm: 'SSO',
      clientId: 'location-api',
      secret: 'EwyqBu7x6yN5NHMOn0CS71B5D7rzf8Gq',   
      tokenValidation: TokenValidation.NONE,
    })
```

Unfortunately i still get the following log:

```
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [NestFactory] Starting Nest application...
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM    WARN [KeycloakConnectModule] Token validation is disabled, please only do this on development/special use-cases.
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [InstanceLoader] KeycloakConnectModule dependencies initialized +2ms
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [InstanceLoader] AppModule dependencies initialized +2ms
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [RoutesResolver] AppController {/api/location}: +15ms
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [RouterExplorer] Mapped {/api/location, GET} route +7ms
locationapi_1  | [Nest] 81  - 06/01/2022, 8:17:45 PM     LOG [NestApplication] Nest application successfully started +7ms
locationapi_1  | [Nest] 81  - 06/01/2022, 8:18:04 PM VERBOSE [Keycloak] User JWT: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJQOGtRTWJHNk9USTZBQnVvdy1Ea2RpV1BMWml5UXdJMC05SUkyRmJmQk80In0.eyJleHAiOjE2NTQxMTQ5NjcsImlhdCI6MTY1NDExNDY2NywianRpIjoiYmQwMjI0MmEtZjZiMy00YTExLThmYWQtNTZiMDY0MDBhMzFkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL1NTTyIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI4ZjRhZTdkYS00NDYwLTQ4YTQtYTM3MC0xZGMxMjhjY2Y3NDUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjb25zdW1lciIsInNlc3Npb25fc3RhdGUiOiJiMDJhNTA3My05NjJmLTRhOTYtYTIyOS1jZDNlZWJjNDY2M2QiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1zc28iLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6ImIwMmE1MDczLTk2MmYtNGE5Ni1hMjI5LWNkM2VlYmM0NjYzZCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkRlbW8gVXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6ImRlbW8iLCJnaXZlbl9uYW1lIjoiRGVtbyIsImZhbWlseV9uYW1lIjoiVXNlciIsImVtYWlsIjoiZGVtb0BkZW1vLmNvbSJ9.Ko2nxDYih4gWelYk_9whdfSWLDUGHW7RUQ1oDuIY7lX4pO4SlfS1mc1qlgAmqoG2EA_cdsw3u8uUZsKCacjvgi1SHbM9lxS4SElErqzAjeVed9bR7TKFidFoIUTMUH2qsFY5bw5Adi5TbX74u6MisrfrM7SQhO5PGTM6jkK-a8T3Xss_tS8HosYodgNG7BkMMQ2NDwNOAMZpMMvdTK-Cb8NE57i9ZaD4gU4XDSiZqrmK9MYX5piHvWINumOom5Gik-CuIm_b93NSxpE9hjl6U-7QyRaKU2FZjX_bVZL6WL66VgzvxV6kLx1RFW-EK37dXgMUsYeJHKpHkaTMwl-tIA
locationapi_1  | [Nest] 81  - 06/01/2022, 8:18:04 PM    WARN [Keycloak] Cannot validate access token: Error: Grant validation failed. Reason: invalid token (wrong ISS)
```

Any ideas? 😢

**Comment by lieberlois** [comment]
If anybody comes across the same problem, this ENV variable fixes the issue

```yaml
version: "3"

services:

  keycloak:
    image: jboss/keycloak:16.0.0
    ports:
      - 8080:8080
    environment:
      # Necessary for issuer validation
      # (sets the issuer to http://keycloak:8080/auth rather than localhost)
      - KEYCLOAK_HOSTNAME=keycloak
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm.json"
    volumes:
      - ./keycloak/realm.json:/opt/jboss/keycloak/imports/realm.json
      - ./keycloak/keycloak-add-user.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json
```
